language: node_js
node_js:
- '8'
script:
- eval "$(ssh-agent -s)"
- ssh-add $HOME/.ssh/technopark
- npm run build
- scp -r ./dist root@92.53.78.240:~/
before_install:
- openssl aes-256-cbc -K $encrypted_cff8668a0280_key -iv $encrypted_cff8668a0280_iv
  -in technopark.enc -out $HOME/.ssh/technopark -d
